language: ruby
cache:
  bundler: true
  yarn: true

rvm:
  - 2.4.0

node_js:
  - 7.7.1

sudo: required

notifications: # set notification options
  email: false

services:
  - postgresql

before_script:
  - psql -c 'create database challenges_test' -U postgres
  - bundle exec rake db:setup

before_install:
  - nvm install 7.7.1
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

install:
  - bundle install
  - yarn install

script:
  - bin/test

env:
  global:
    RAILS_ENV=test
